package itunessearch.request;

import java.io.IOException;
import java.util.Map;

/**
 * Represents an Http itunessearch.request to the iTunes server.
 */
public interface Request {

    String SEARCH_URL_BASE = "https://itunes.apple.com/search?";
    String LOOKUP_URL_BASE = "https://itunes.apple.com/lookup?";

    /**
     * Returns a String url by combining the user specified url parameters and the base iTunes Search url
     * ("https://itunes.apple.com/[search? || lookup?]").
     */
    String createUrl();

    /**
     * Returns a String url to get the next page of results.
     */
    String nextPageUrl();

    /**
     * Returns a Request object with the offset set for the next page.
     */
    Request nextPageRequest();

    /**
     * Convenience method for sending an Http itunessearch.request to the url generated by createUrl().
     *
     * @throws IOException if it could not send the itunessearch.request.
     */
    Response sendRequest() throws IOException;

    /**
     * Returns the parameter map containing the
     */
    Map<String, String> getParamMap();

    /**
     * Returns the current offset.
     */
    int getCurrentOffset();
}
