package main;

import java.util.Map;

/**
 *
 */
interface Request {

    /* Valid keys for the request url. */
    enum Keys {
        TERM,
        COUNTRY,
        MEDIA,
        ENTITY,
        ATTRIBUTE,
        LIMIT,
        LANG,
        VERSION,
        EXPLICIT,
        OFFSET;

        @Override
        public String toString() {
            return super.toString().toLowerCase();
        }
    }

    /**
     * Returns a String url by combining the user specified url parameters and the base iTunes Search url
     * ("https://itunes.apple.com/search?").
     */
    String createUrl();

    /**
     * Convenience method for sending an Http request to the url generated by createUrl().
     */
    Response sendRequest();

    /**
     * Returns the parameter map containing the
     */
    Map<Keys, String> getParamMap();
}
