package request;

import java.util.Map;

/**
 *
 */
public interface Request {

    /**
     * Returns a String url by combining the user specified url parameters and the base iTunes Search url
     * ("https://itunes.apple.com/search?").
     */
    String createUrl();

    /**
     * Returns a String url to get the next page of results.
     */
    String nextPageUrl();

    /**
     * Returns a Request object with the offset set for the next page.
     */
    Request nextPageRequest();

    /**
     * Returns a String url for the page at the specified offset.
     */
    String getPageUrlAtOffset(int offset);

    /**
     * Convenience method for sending an Http request to the url generated by createUrl().
     */
    Response sendRequest();

    /**
     * Returns the parameter map containing the
     */
    Map<String, String> getParamMap();

    /**
     * Returns the current offset.
     */
    int getCurrentOffset();
}
