package request;

import java.util.Map;

/**
 *
 */
public interface Request {

    /* Valid keys for the request url. */
    enum Keys {
        TERM,
        COUNTRY,
        MEDIA,
        ENTITY,
        ATTRIBUTE,
        LIMIT,
        LANG,
        VERSION,
        EXPLICIT,
        OFFSET;

        @Override
        public String toString() {
            return super.toString().toLowerCase();
        }
    }

    /**
     * Returns a String url by combining the user specified url parameters and the base iTunes Search url
     * ("https://itunes.apple.com/search?").
     */
    String createUrl();

    /**
     * Returns a String url to get the next page of results.
     */
    String nextPageUrl();

    /**
     * Returns a Request object with the offset set for the next page.
     */
    Request nextPageRequest();

    /**
     * Returns a String url for the page at the specified offset.
     */
    String getPageUrlAtOffset(int offset);

    /**
     * Convenience method for sending an Http request to the url generated by createUrl().
     */
    Response sendRequest();

    /**
     * Returns the parameter map containing the
     */
    Map<Keys, String> getParamMap();

    /**
     * Returns the current offset.
     */
    int getCurrentOffset();
}
